### ISSUE TITLE
Multiview Embeddings 

### ISSUE THREAD

**Issue by pshankinclarke** [SugiharaLab/pyEDM#16]
I want to find the optimal embedding for the  DataFrame : 

```
          Time  zPlankton     zTemp
0   2017-06-05   -0.26045  1.166239
1   2017-06-07   -0.26045  1.191292
2   2017-06-08   -0.26045  2.966024
3   2017-06-09   -0.26045  1.228036
4   2017-06-10   -0.26045  2.308131
..         ...        ...       ...
513 2019-11-26   -0.26045  0.991427
514 2019-11-27   -0.26045  0.982501
515 2019-11-28   -0.26045  0.760553
516 2019-11-29   -0.26045  0.609049
517 2019-11-30   -0.26045  0.625454

```

I used the function :

```
E = pyEDM.EmbedDimension(dataFrame = dataframe ,
                    lib= training,
                    pred = testing,
                    Tp = 5,
                    columns = 'zPlankton zTemp',
                    target = 'zPlankton')

```
with the call : 

```
training = str(1) + " " + str(130)
testing =  str(131)+ " " +str(170)
E = pyEDM.EmbedDimension(dataFrame = dataframe ,
                    lib= training,
                    pred = testing,
                    Tp = 5,
                    columns = 'zPlankton zTemp',
                    target = 'zPlankton')


```

and it returned the dataFrame :

```
       E       rho
0   1.0  0.012601
1   2.0  0.003388
2   3.0  0.048605
3   4.0  0.158140
4   5.0  0.289097
5   6.0  0.344303
6   7.0  0.523114
7   8.0  0.641576
8   9.0  0.601631
9  10.0  0.340248
```

I wanted to see if I could replicate this result with the function : 

```
def MultiviewEmbedding(dataFrame,lib,pred,D,Tp,columns,target):
    Es = list(range(1,10))
    RMSEs = []
    for E in Es:
       print(E)
       info = pyEDM.Multiview(dataFrame = dataFrame,
                       lib = lib,
                       pred = pred,
                       E =  E,
                       D = D,
                       Tp = Tp,
                       knn = E + 1,
                       columns = columns,
                       target = target)
       RMSEs.append(info.get('View')['RMSE'].tolist()[0])
    return pd.DataFrame({'E' : Es, 'RMSE': RMSEs})
```

with the call : 

```
E = MultiviewEmbedding(dataFrame = dataframe ,
                       lib= training,
                       pred = testing,
                       D = 2,
                       Tp = 5,
                       columns = 'zPlankton zTemp',
                       target = 'zPlankton')


```

Where the smallest RMSE value would correspond to the best forecast prediction skill. However it returned the dataFrame: 

```
   E      RMSE
0  1  2.494547
1  2  2.483781
2  3  2.504601
3  4  2.531073
4  5  2.504950
5  6  2.519986
6  7  2.515340
7  8  2.505734
```
with the warnings : 

```
1
Multiview() Set view sample size to 2
WARNING: Multiview(): multiview ensembles 2 exceeds the number of available combinations: 1.   Set to 1
2
Multiview() Set view sample size to 2
3
Multiview() Set view sample size to 3
4
Multiview() Set view sample size to 5
5
Multiview() Set view sample size to 6
6
Multiview() Set view sample size to 8
7
Multiview() Set view sample size to 9
8
Multiview() Set view sample size to 10
9
Multiview() Set view sample size to 12
```
In the dataFrame returned by the function `EmbedDimension` the E with the largest (i.e best) forecast skill was E = 8, but in the dataFrame returned by the function MultiviewEmbedding (i.e. the function that I wrote) the E with the smallest (i.e. best) RMSE was E = 2. My questions are : 

1.  Can you clarify the error : `WARNING: Multiview(): multiview ensembles 2 exceeds the number of available combinations: 1.   Set to 1`
2. Do rho and RMSE have an inverse relationship? That is, should the E with highest rho correspond to the E with the lowest RMSE for a forecast?

**Comment by SoftwareLiteracy** [comment]
That's an interesting question: can Multiview be used to find an optimal embedding dimension for a multivariate dataset that is time delay embedded to E.  Perhaps, but, that is not the intended use of Multiviiew.  EmbedDimension and Multiview are asking two fundamentally different questions.

EmbedDimension helps chose a proper time delay embedding dimension.
Multiview helps chose informatic variables from a multivariate state space. 

EmbedDimension asks the question: What time-delay embedding dimension gives optimal predictability, and therefore we presume, does the best job representing the underlying dynamics. What is the optimal E?

Multiview asks the question: What combination of variables from a multivariable state space gives the best predictability, and therfore we presume, do the best job representing the underlying dynamics.

1. Can you clarify the error : `WARNING: Multiview(): multiview ensembles 2 exceeds the number of available combinations: 1. Set to 1`
-- Recall that Multiview creates D-dimesional combinations of the variables listed in columns.  E specifies the time delay embedding dimension of each variable.  You have 2 variables in columns. With E = 1, there is only 1 2-dimensional combination available, So, the warning is generated that only 1 multiview combination is available. 
-- With E = 2, your state space is 4-dimensional: zPlankton, zPlankton(t-1), zTemp, zTemp(t-1). How many ways can 4 variables be combined in pairs?  6,  Per the documentation, if not specified, then multiview is sqrt(C) = sqrt(6) = 2.4, so 2.  And so on...
 
2. Do rho and RMSE have an inverse relationship? That is, should the E with highest rho correspond to the E with the lowest RMSE for a forecast?
-- It may be true in most cases, but generally, no.  Depends on the data and model parameters.

**Comment by pshankinclarke** [comment]
Thanks for the response! For clarification, the question that I am trying to answer is : 

- Given concurrent temperature and plankton abundance data (i.e. my columns) what is the optimal embedding dimension (i.e. E) argument for the`Multiview` function such that it produces the best Simplex forecast for plankton abundance (i.e my target)?

`EmbedDimension`  finds the forecast skill of Es by evaluating Simplex predictions as a function of E. My function (i.e. `MultiviewEmbedding`) tries to replicate the results of  `EmbedDimension`  by finding the RMSEs of the Simplex projections returned by `Multiview` as a function of E. If both `EmbedDimension` and `MultiviewEmbedding` are functions of E that return Simplex forecasts with the same columns and target, is one of the them a better answer to my question? Thanks!

**Comment by SoftwareLiteracy** [comment]
My understanding is that one normally applies `EmbedDimension` to a single variable.  This is consistent with Takens embedding theorem: what time-delay embedding dimension best represents the underlying dynamics expressed in a single variable time series observed from the system dynamics.  

`EmbedDimension` allows the use of multiple variables, however, theoretically, this could be shaky ground since Takens' theorem applies to a single variable observed from the system, not multiple variables.  And if the multiple variables are in fact not part of the same dynamical system... then surely the use of `EmbedDimension` is an overreach. 

We need more expertise than I have to answer this question: is there a multidimsional version of Takens theorem?

In the meantime, my suggestion is to use `EmbedDimension` on individual variables, providing an indication of the dimensionality of each.  Practically, using extra dimensions does not incur a penalty modeling the dynamics as long as enough data is avaiable and the dimensionality remains "low".   If Temp has E = 5 and Plankton has E = 3, then I would use `Multiview` with E = 5.  

Again, `Multiview` is asking a different question. While I do appreciate the catch-22 nature of trying to use `EmbedDimension` and `Multiview` in concert, to me, the questions they pose are fundamentally different and trying to recreate one with the other is problematic.  But interesting!

**Comment by pshankinclarke** [comment]
Thank you for the insights! I like your methodology for finding the optimal E. It makes sense that the larger E would correspond to the more "disentangled" manifold if Temp and Plankton are emergent from the same state-space manifold. Is E <= 5 considered a "low" dimensionality? Also if two variables have vastly different E's (e.g. E = 8 and E = 2) is it evidence that the variables are emergent from two different state-space manifolds or does it also depend on the rhos for the E's or is it purely circumstantial? Thank you!

**Comment by SoftwareLiteracy** [comment]
_Is E <= 5 considered a "low" dimensionality?_ 
In my opinion, yes.  Less than 10 or-so depending on the application/data makes sense to me.  Perhaps sometimes in the range of 10-15 ?  It all depends on the dynamical system.  

The way I like to think about it is that a purely stochastic, random system is, in a sense, infinite dimensional, or at least high-dimensional.  Assessing good estimates of dimensionality has been a central problem since nonlinear dynamical systems theory emerged in the 1970's.  There is much literature on this issue you may wish to review.

_If two variables have vastly different Es (e.g. E = 8 and E = 2) is it evidence that the variables are emergent from two different state-space manifolds?_
In a sense, the observable universe creates a state-space manifold.  Deciding that variables "belong" to the same dynamical system is imo part of the data discovery process.  When possible this can be guided by physical relevance.  It doesn't seem to me that different E's say much about this.  One way is to use CCM.  [Sugihara et al. argue](https://science.sciencemag.org/content/338/6106/496) that variables which share a dynamical system (manifold) are causally linked.  I think that a combination of CCM and perhaps Multiview are ways of approaching this question.  At least that's the approach I've been using.

Very good questions indeed.  I would certainly like to hear the views of those more aware of EDM and it's applications...
