### ISSUE TITLE
Embed

### ISSUE THREAD

**Issue by pshankinclarke** [SugiharaLab/pyEDM#18]
I am using `pyEDM==1.7.5.0` with the` pyEDM.Embed()` function in order to generate  embeddings for the columns of the dataframe : 

```
    dataFrame = pd.DataFrame({'T': random.sample(range(10,200),150),
                              'W': random.sample(range(10,200),150),
                              'V': random.sample(range(10,200),150)})
```

Which produces the dataframe : 
```

       T    W    V
0    108   99  109
1     27   30  174
2    158   61   34
3    161   17  169
4     52  150  112
..   ...  ...  ...
145   83  147   91
146  121  105   16
147  122   14  147
148   11  180   72
149  198  163  136

```

However when I use the function : 
```

    embed_cols = pyEDM.Embed(dataFrame = dataFrame,
                             E = 2,
                             columns = ['T','W',' V'])
```

I get the following error : 

`RuntimeError: EDM::Embed(): Failed to find column T in dataFrame with columns: [ W V  ]`

I am wondering whether this is a bug in the software or if there's something missing on my end?

**Comment by SoftwareLiteracy** [comment]
Thanks for the evaluation.  This is because all input .csv files or data frames are required to have a time vector as the first column.  This is mentioned in the [online docs](https://sugiharalab.github.io/EDM_Documentation/parameters/) for the `dataFile` and `dataFrame` parameters, and, in the [API docs](https://github.com/SugiharaLab/pyEDM/blob/master/doc/pyEDM.pdf) in the **Usage** section. 

In your example, the `T` column is presumed to be a time vector, not one of the variables available for embedding.

**Comment by pshankinclarke** [comment]
Great, thanks!
