### ISSUE TITLE
Suggestion: Indexing

### ISSUE THREAD

**Issue by pmahon3** [SugiharaLab/pyEDM#28]
I'm not sure if it would make sense to make this change for the user side of things although it might be more trouble than it's worth. 

Since python is zero-indexed it might make sense to implement library and prediction string arguments as zero-indexed as well.  

I understand the zero indexing shift is done in Parameters::Validate() here: [`library.push_back( j - 1 ); // apply zero-offset`](https://github.com/SugiharaLab/pyEDM/blob/ed70fb6adee2ce86161fdff6a1033b2fe69a00f6/cppEDM/src/SMap.cc#L285)``

I assume this is an artifact of porting the c code to rEDM?

**Comment by SoftwareLiteracy** [comment]
Thanks for the review and suggestion.

Indeed, this is implemented in the cppEDM core as you note. I did debate this when the code was developed. As a longtime R user (started with version 1.4 at the turn of the Century) I had, and have, a Love : Hate relationship with R.  Can write volumes on both sides.  One of the things R "got right" imo is to not use 0-based indexing for the user interface.  0-based indexing is an artifact from the 1960's B (precursor to C), and makes sense at a low-level.

Today, most users of R and Python are not (imo) computer scientists, much less software/hardware developers, so that 0-based indexing is a source of error and misunderstanding.  It seems natural to me that EDM refers to library (`lib`) and prediction (`pred`) segments in the input time series using actual row numbers of the data, starting at 1. Plus, the legacy rEDM wrapper also used this, so there is a backward compatibility argument. 

Most mathematical expressions (vectors etc.) do not normally use 0-based indexing. And, many newer, high-level languages (Julia, Matlab, Mathmatica, Smalltalk, Wolfram Language) also do not use 0-based indexing. 

Thereby, I think that 0-based indexing for the user interface should not be used in EDM. 

One day... something like Python or Wolfram will be the dominant, universal programming language, and I hope it doesn't use 0-based indexing ; ).

**Comment by pmahon3** [comment]
Cool, that makes sense! Didn't know that about B, that's cool 

I've grown up with a 50/50 R Python split and every time I switch from one to another I complain about what it isn't for a bit aha. It sounds like there isn't a lot of development on top of pyEDM that would justify it. 

Here's to the day we find indexing world peace.
