### ISSUE TITLE
Computation Time Issue

### ISSUE THREAD

**Issue by SteinPanyu** [SugiharaLab/pyEDM#31]
Hi, 

I am running some CCM code, may I ask if there is any way to reduce the computation time in pyEDM?
I am doing multiple subject CCM. For each subject, the length of data is around 200. The number of subjects is around 55.
It takes me almost half a day to run the code. 

Could you give me any suggestions say modifying parameters to reduce the time? 
such as **Libsizes** or **sample** in CCM( ) 
or modifying **predict** or **lib** in EmbedDimension( ) or PredictNonlinear( )

Any help would be appreciated.

**Comment by SteinPanyu** [comment]
Btw, I still cannot understand paramters **random** and **sample** in CCM( )? How come we randomly sample the library data in CCM( )?

**Comment by SoftwareLiteracy** [comment]
The best way to understand CCM parameters is to read the reference publication: 
Sugihara G., May R., Ye H., Hsieh C., Deyle E., Fogarty M., Munch S., 2012. Detecting Causality in Complex Ecosystems. [Science 338:496-500](https://science.sciencemag.org/content/338/6106/496).

CCM randomly samples state-space vectors from the library to represent partial state-spaces to investigate the hypothesis that convergence of the cross mapped prediction skill (information content) as the state-space is increasingly populated indicates a causal link.

The `random` parameter should be left at it's default `random = True`, otherwise one is not performing CCM.

`sample` is the number of times a specific `libSize` is randomly sampled, resulting in an average representation of the cross mapped prediction skill.  Large `sample` produces smoother estimates, at the cost of increased run time.  `sample = 100` is a commonly used value for final analysis, Using smaller values (20,50) for data discovery can have a noticeable impact on run time.

The number of library sizes that are evaulated also impacts run time.  For data exploration a rather sparse set could suffice.  One wants to demonstrate convergence, so a few small values, a mid value, and a value at/near full library size. 

Since `CCM()` is an evaluation over a range of library sizes, one obvious way to decrease wall time is to paralellize over the library sizes.  The repository has such an application [CCM-Multiprocess.py](https://github.com/SugiharaLab/pyEDM/blob/master/pyEDM/etc/apps/CCM-Multiprocess.py)

Another common use case is to compute a CCM matrix over multiple pairs of data vectors. This can also be parallelized by creating an iterable of the cross variable names (perhaps as tuples), then applying the Python `multiprocessing Pool` as in the foregoing example. 

Example of reducing run time with selective `libSizes`
```Python
>>> from time import time
>>> from pyEDM import *
>>> df = sampleData['Lorenz5D']
>>> df.shape
(1000, 6)
>>> df.columns
Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5'], dtype='object')
>>> start = time(); CCM( dataFrame = df, E = 5, columns = "V5", target = "V1", sample = 50, libSizes = "20 50 100 500 900 980" ); end = time(); print( 'Elapsed:', round(end - start, 3), 'seconds' )
   LibSize     V5:V1     V1:V5
0     20.0  0.671163  0.465948
1     50.0  0.824342  0.587274
2    100.0  0.864788  0.643224
3    500.0  0.905727  0.775061
4    900.0  0.914879  0.810749
5    980.0  0.916208  0.815429
Elapsed: 12.981 seconds
>>> 
>>> start = time(); CCM( dataFrame = df, E = 5, columns = "V5", target = "V1", sample = 50, libSizes = "20 980 50" ); end = time(); print( 'Elapsed:', round(end - start, 3), 'seconds' )
    LibSize     V5:V1     V1:V5
0      20.0  0.671163  0.465948
1      70.0  0.851076  0.627287
2     120.0  0.872294  0.667364
3     170.0  0.883287  0.698120
4     220.0  0.887819  0.720344
5     270.0  0.893610  0.735376
6     320.0  0.896269  0.747577
7     370.0  0.898734  0.758152
8     420.0  0.903163  0.765555
9     470.0  0.903804  0.771761
10    520.0  0.906044  0.778519
11    570.0  0.908436  0.783370
12    620.0  0.909062  0.788510
13    670.0  0.910442  0.793311
14    720.0  0.911544  0.797190
15    770.0  0.912439  0.802036
16    820.0  0.914013  0.805408
17    870.0  0.914372  0.808981
18    920.0  0.915230  0.811859
19    970.0  0.916002  0.814784
Elapsed: 47.923 seconds
```

**Comment by SoftwareLiteracy** [comment]
Suggested techniques:

  1. Reduce the number of `sample` (for data exploration).
  2. Reduce `libSizes` to a small set spanning the library.
  3. Since CCM() is an evaluation over a range of library sizes, paralellize over library sizes. See [CCM-Multiprocess-LibSizes.py](https://github.com/SugiharaLab/pyEDM/blob/master/pyEDM/etc/apps/CCM-Multiprocess-LibSizes.py).
  4. Compute a CCM matrix over the columns of a DataFrame. Parallelized by creating an iterable of the column variable names against a target. See [CCM-Multiprocess-Columns.py](https://github.com/SugiharaLab/pyEDM/blob/master/pyEDM/etc/apps/CCM-Multiprocess-Columns.py).

**Comment by SteinPanyu** [comment]
Thanks for your detailed reply!
