### ISSUE TITLE
SMAP RuntimeError: VectorColumnNames

### ISSUE THREAD

**Issue by sfruf** [SugiharaLab/pyEDM#34]
Hello! 

I'm attempting to use SMAP for prediction based on an embedded dataframe and I'm getting a strange error. Despite the fact that the dataframe has the column 'x1(t-0)' in it before it gets passed to SMAP, SMAP raises an error that it's missing. Code/error screen shots below. Thanks!  
 
<img width="1141" alt="Screen Shot 2022-10-31 at 8 45 24 AM" src="https://user-images.githubusercontent.com/44092105/199011453-68276d77-3631-440a-963e-f20ebb8978dd.png">

<img width="1728" alt="Screen Shot 2022-10-31 at 8 45 34 AM" src="https://user-images.githubusercontent.com/44092105/199011728-8f77e3ea-14d0-4262-945b-fe9008d1bb3d.png">

**Comment by sfruf** [comment]
Thanks for your fast response! 

Wouldn't that only be true if the input data frame were not embedded already? I'm using pyEDM.Embed [which drops the time index column](https://sugiharalab.github.io/EDM_Documentation/edm_functions/#embed) in the previous step.

**Comment by SoftwareLiteracy** [comment]
Right. In `Embed()` : The time column is not included in the returned DataFrame. 

Since `Embed()` doesn't perform any EDM operations (`Simplex`,`SMap`, etc) it doesn't have use for the time vector. On one hand, a time vector is irrelevant to a time-delay embedding since the `tau` parameter specifies rows. But, by not returning the time vector, it is a wrinkle to use it seamlessly with the EDM functions, 

At the momnent, the user needs to add a time vector to the output of `Embed()`. 

Perhaps we can add a parameter to `Embed()` to return a data frame with the time vector.

**Comment by sfruf** [comment]
Thanks, that got it working. 

It's confusing that the various EDM functions don't naturally work well together. It might be worth adding to the Embed() documentation that you'll need to add the time vector back in for the output to work with other EDM functions.
