### ISSUE TITLE
Question about the concept and how to set "lib" and "pre" in the function "EmbedDimension"

### ISSUE THREAD

**Issue by ecosan327** [SugiharaLab/pyEDM#38]
Hi,

I have read the related issue of how to decide the `lib` and `pre` in the function `EmbedDimension`. However, I couldnt fully understand the concept of these two parameters corresponding to the calculation in some papers.

(1) From the explanation from Simplex projection walkthrough, I am wondering which part in the below figure corresponds to  `lib` and `pre` ? 
Is the total number of points of the red line the `pre` value? And is the total number of points in one blue segment the  `lib`  value?
![Screenshot from 2023-04-25 15-23-13](https://user-images.githubusercontent.com/90598608/234204369-32b6cba5-87f1-4c09-92ac-300ed402843a.png)
(the Simplex projection walkthrough: http://opetchey.github.io/RREEBES/Sugihara_and_May_1990_Nature/Simplex_projection_walkthrough.html)

(2) Suppose I have a time series data with 1000 data points. If I use nonoverlapping `lib` and `pre`, should the sum value of `lib` and `pre` covers the 1000 points (ex: `lib=1~700` and `pre=701~1000` )? I am not sure how to set the range of the `lib` and `pre` in one time series. Or is it ok that we just choose a small range of  `lib` and `pre` (ex:  `lib=1~100` and `pre=500~600` )?

(3) Continued from the preceding question(2), will the determination of which part of the time series should belong to `lib` or to `pre` be influenced by the dynamics of the time series? For exmaple, the data dynamics in one time series array is not repeated(i.e. no repeated pattern across the whole time series). If that's the case, how should I determine the which range in time series for `lib` and `pre`?

(4) In the issue #26, the discussion mentioned that for the later-on CCM analysis, we can set ` lib = pred = N - tau * E` in the function `EmbedDimension` to find the `E`. However, we dont know `E` first and that's the value we want to find, right? I am a bit confused of what value sholud I set the  `lib` and `pre` in the function `EmbedDimension` here. 
Also, N is the total number of data points of our time series?

**Comment by SoftwareLiteracy** [comment]
Thank you for the detailed question.

Simply, `lib` specifies the time series indices (rows) used to create the _library_ (state-space) from which predictions are made.  The library is an E-dimensional matrix [ len( `lib` ) rows x E columns ]. Ideally, the library encapsulates the complete dynamical behavior of the system. `pred` is the time series indices (rows) at which predictions are made to time interval `Tp`. Note that `Tp` can be zero or negative. 

`lib` and `pred` are problem  and question dependent.  That is, what is the question being asked regarding the data? 

In a operational forecast system one is likely to use all available data for the library, the complete past history, while `pred` is set to the last observed data point. 

In _data discovery_  and parameter selection (`E`, `tau`...) `lib` and `pred` may be degenerate (overlapping for the entire time series) as one seeks to asess how well a particular model (set of parameters) fits (forecasts) the data. CCM is an example. 

For model validation, it is common practice to have disjoint `lib` (_training data_ in machine learning parlance) and 'pred` (_validation_ or _withheld_ data). 

---

Specific questions:

#### 1) From the explanation from Simplex projection walkthrough, I am wondering which part in the below figure corresponds to lib and pre ?

It is not explcitly specified in the walkthrough. I would guess it corresponds to the operational forecast case where `lib` is the entire data set (N values) and `pred` is the last observed data point (1 value). 

#### 2) Suppose I have a time series data with 1000 data points. If I use nonoverlapping lib and pre, should the sum value of lib and pre covers the 1000 points (ex: lib=1-700 and pre=701-1000 )?

Simple answser is no.  Selection of `lib` and `pred` are problem / question dependent. The case here corresponds to a situation where data rows 1-700 encapsulate the system dynamics, and the model (algorithm, E, tau, ...) is evaluated over the so-called withheld data in rows 701-1000.

#### 3) will the determination of which part of the time series should belong to lib or to pre be influenced by the dynamics of the time series? 

Yes. As above the selection is problem / question dependent: Ideally, the library encapsulates the complete dynamical behavior of the system.

#### 4) CCM analysis, we can set  lib = pred = N - tau * E in the function EmbedDimension to find the E. However, we dont know E first and that's the value we want to find, right? I am a bit confused of what value sholud I set the lib and pre in the function EmbedDimension here. Also, N is the total number of data points of our time series?

Right. `EmbedDimension` is to help assess data / models that best represent the dynamics. It evaluates simplex models across a spectrum of `E` values to identify a minimal embedding dimension for use in CCM, SMap, Simplex...

What values of `lib` and `pred` to use in `EmbedDimension` ?  A reasonable starting point is `lib` == `pred` == [1,N] where N is the number of data points. This evaluates models over the entire data set. Depending on the application / question, it is also possible to use disjoint `lib` and `pred`.

**Comment by SoftwareLiteracy** [comment]
This shows the TentMap data is low dimensional, with E = 2 representing a reasonable embedding dimension.  As you mention, this result is stable whether one uses 100 or 900 points for the library, so it seems 100 points is sufficient to represent the dynamics. 

In the case of a saturation as shown above, one would normally choose the lowest E, here E = 2 to keep the model as low-dimensional as possible. Although using E = 3 or 4 should not impact the analysis. This is a well-known criteria that getting the minimal embedding dimension is critical, while using a somewhat larger one does not usually impact the results. 

Of course, every problem is data dependent, so the data discovery phase as here is a crucial step.  For example, if the model has different embedding time lag (tau), Tp, exclusion radius etc... Here's an example that evaluates over a range of tau finding for this data, E = 2 is a good choice. With "real world" data, the combination of E and tau can be important, as it effecteively "samples" different temporal resolutions of the dynamics.  But starting with the default of tau = -1 is a reasonable choice.

```python
from pyEDM import *
from matplotlib import pyplot as plt

TentMap = sampleData['TentMap']

def ED( tau = -1 ) :
    df = EmbedDimension( dataFrame = TentMap, lib = '1 900', pred = '1 900',
                         maxE = 8, Tp = 1, tau = tau, columns = 'TentMap',
                         target = 'TentMap', numThreads = 8, showPlot = False )
    return df

taus = [-1,-2,-3,-4]

ED_list = [ ED(tau) for tau in taus ]

for i in range( len(ED_list ) ):
    plt.plot( ED_list[i]['E'], ED_list[i]['rho'], label = taus[i] )

plt.legend( title = 'tau' )
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/6317942/234536718-b2d5415b-56e9-457e-9f32-377ee385b4a5.png)

**Comment by ecosan327** [comment]
Thank you for the extended suggestion! Here are some thoughts that I was thinking about:

(1) From the TentMap exmaple image of different `tau` above, does it mean that the best combination of ` [E, tau] `is `[2, -2]`, since the orange line has the highest `rho` at ` [E=2, tau=-2] `and a more obvious peak(at least compared to the blue line` [tau=-1] `)?

(2) Could you elaborate more about the meaning of `tau` as different temporal resolutions of the dynamics? Can we regard `tau` as the intrinsic time scale of the dynamics(If so, it means the larger the `tau`, the change of the dynamics of the system is slower.)? And we should also apply this `tau` value to CCM calculation?
I found it hard to understand the meaning of `tau` from the paper of 1990 George Sugihara simplex paper.

(3) I tried to apply the different `tau` to my own data. And it indeed shows different trend for different `tau` value:
![ttt](https://user-images.githubusercontent.com/90598608/234754490-29359ab1-8840-4c90-8bbf-45eba7ece7c7.png)
For example, the red line(`tau=-4`) has a peak around `E=4`, however the blue line(`tau=-1`) peaks around `E=3`.
In this case, which combination should I choose for the lateron CCM? I think maybe I still need to choose based on the best `rho` (i.e. the blue line of `E=3,tau=-1` ).

**Comment by SoftwareLiteracy** [comment]
Here are my thoughts:

1. _Does it mean that the best combination of [E, tau]is [2, -2], since the orange line has the highest rho at [E=2, tau=-2] and a more obvious peak(at least compared to the blue line[tau=-1])?_  I don't think `EmbedDimension` is the right tool to select tau, but to evaluate E, tau once a tau is selected. The intial estimate of E can be done with default tau = -1. 

3. _Can we regard tau as the intrinsic time scale of the dynamics (If so, it means the larger the tau, the change of the dynamics of the system is slower.)? And we should also apply this tau value to CCM calculation?_  I don't think tau is generally the intrinsic time scale of the dynamics. Once you identify the appropriate tau, then yes, it can be used in all EDM analysis.  The way I think of the [ E, tau ] combination is in terms of the state space E-dimensional vectors.  If you do a time-delay embedding with [ E, tau ], then each state space vector "spans" a time period of `E*tau`, but sampled at an interval of tau.  Effectively, the state space vectors "span" or "sample" longer timescales in the data (via the embedding process that time-delays the samples into a state vector) as E*tau increases.  At least that is my notion... very interested to hear if others agree/disagree...

4. _I tried to apply the different tau to my own data. And it indeed shows different trend for different tau value..._ It is perhaps better to not select anything other than E using EmbedDimension.  Selection of tau, exlusionRadius etc should be done based on other considerations.  Once they are set, then perhaps return to EmbedDimension to refine the model parameters and select a different E. This approaches the more nuanced, but very important issues of parameter selection.  For example, is there serial correlation (autocorrelation) in your data?  If there is, is this something you want to include in the dynamics and analysis?  If there is, then small E*tau results may be dominated by serial correlation.  If you chose to ignore serial correlation that is present, the `exclusionRadius` can be used.  How to select an exclusionRadius?  I normally look at the decay in mutual information versus time lag.  The jpyEDM jupyter notebook has this function. 

One more comment is that there not a great deal of difference between correlation of 0.88 and 0.91.  Your data shows the largest increase from E = 1 to E = 2, so E = 2 is a reasonable starting point. If you decide that tau = -2 is a good choice for the data, then E = 3 or 4 are good choices. 

All good questions toward the "art of scientific computing" and proper use of the tools.

**Comment by ecosan327** [comment]
Thank you for the detailed reply! =)
