### ISSUE TITLE
Question about choosing tau

### ISSUE THREAD

**Issue by kcnguyen3191** [SugiharaLab/pyEDM#39]
Hi,

I have been trying to figure out how to choose `tau` for embedding before running CCM. I have been choosing the `tau` based on the first minimum of mutual information (MI) as suggested by the authors in this [paper](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.67.066210). In my case, MI suggests that `tau=10`, but I got a much lower prediction skill compared to `tau=1` (0.6 vs. 0.9). Is there a better way to choose `tau`? Or should I go with `tau=10` as suggested by MI?

In issue #38 , it was mentioned that if we ignored the autocorrelation, we could use `exclusionRadius`. Could you explain more on how to choose `exclusionRadius` based on mutual information?

Thanks!

**Comment by SoftwareLiteracy** [comment]
I think there are several questions here, that are somewhat independent. 

I am not able to access the Cellucci (2003) paper, but one has to be in full agreement with their viewpoint: 
>The choice of appropriate embedding parameters (dimension and lag) is crucial to the success of the subsequent analysis. 

#### Mutual information decay
Decay in MI refers to comparing the MI of a time series x(t) against lagged versions of itself. MI<sub>1</sub> = IXY( x(t) : x(t-1) ); MI<sub>2</sub> = IXY( x(t) : x(t-2) ); ... MI<sub>n</sub> = IXY( x(t) : x(t-n) ).  Conventionally, when the decay (decrease) in MI<sub>i</sub> from MI<sub>1</sub> exceeds MI<sub>1</sub> / _e_ it is considered a time-lag at which the data are serially indepenent (uncorrelated in the linear sense). Of course, other thresholds are also used. 

#### Exclusion radius
The question of serial correlation (autocorrelation) is whether or not your data exhibits it, and, if it does, do you wish to include it in the dynamics to be analyzed by EDM?  If the answer is yes, the data has serial correlation, and you want to _exclude_ effects of serial correlation from the analysis, set the `exclusionRadius` parameter to the lag of serial independence. This excludes library nearest neighbors that are within `exclusionRadius` time units of the point being forecast.  This operates on the library, the state space embedding that was created using tau.  So at this point, effects of tau are already present in the embedded state space. 

It was mentioned in [#38 ](https://github.com/SugiharaLab/pyEDM/issues/38) that the [pyEDM jupyter notebook](https://github.com/SugiharaLab/jpyEDM#readme) front end has a gui function to assess the decay in lagged MI. 

The above it soley my opinion / suggestion.  Others may have a better understaning / approach. 

#### How to select tau?
As mentioned in [#38 ](https://github.com/SugiharaLab/pyEDM/issues/38), this is a data / question dependent selection. We must remember that Takens theorem is the base of univariate EDM analysis. I am not sure what the theorem explcitly says about tau.  My understanding is that tau = -1 is the presumed default, and other small values (-2,-3) often do not have a large impact on the results. 

It seems to me that selecting different combinations of E, tau encapsulate different time scales in each library vector.  However, all of the proviso's regarding selection of E apply.

It would be great if someone with a deeper understanding of the implications of tau comments ; )

**Comment by kcnguyen3191** [comment]
Thank you so much for the detailed response! It's very helpful.

Sorry, I would like to clarify that choosing `tau` does not have large impact on the results when running `CCM`. If I understand the algorithm correctly, `CCM` would the entire data set to compute the prediction skills with leave-one-out cross validation method.

However, I have been dividing my data set into training/testing sets. Then, I use the training set as the library to make prediction on the testing set using the `Simplex` function. The prediction skills are computed only the testing set. For my case, I have found the choice of `tau` would affect the accuracy on the testing set. Is this a bad approach if my data set only has ~ 200 time points?

**Comment by SoftwareLiteracy** [comment]
I would not say choosing `tau` is not gauranteed to have large impact on the results when running `CCM`.  Perhaps better to say that `tau` can be an important parameter in creation of the state space library from which EDM functions, including `CCM`, operate. As always, it depends on the data, and the questions. 

My understanding of Takens theorem is that the default of `tau = -1` is sufficient to reconstruct an affine (diffeomorphic) representation of the state space (attractor, manifold).  This should work as long as the dynamics are well represented in the observations. 

Selecting a different `tau` for the time-delay embedding creates a different state space. One hopes that state space also satisfies Takens theorem and creates an affine state space to the actual dynamics. Since the combination of `E`, `tau` govern the temporal scale representeed in each libtary state vector, different time scales of the dynamics will be represented in each library state vector. 

On the question of optimal `tau`, I am not aware of a published work that deeply investigates it.  However, one might be guided by the core principle that model predictability is the fundamental metric by which models (parameters) are evaluated. 

What you describe for `Simplex` is a common approach.  You find that `tau` has an impact on the results. As above, being guided by model predictability to select parameters is reasonable.  However, again, we recall that these methods presume the complete dynamics are represented in the data library.  Increasing `E` and `tau` necessarily reduces the number of library vectors.  With say 100 points, after time delay embedding, are the complete dynamics still represented in the library?  At some point, depending on the dynamics, they will not be if  `E` and `tau` are too large. 

As always, the data and satisfaction of underlying presumptions govern result fidelity. 

Regarding `CCM`: it uses the entire library, It does not have `lib` and `pred` paramters. Internally  `lib` = `pred`, and predictions to evaluate model predictability are made over the entire data set.  However, predictions are made from random subsamples of the library according to the `libSizes`.  EDM functionas always exclude the prediction point itself from the library when making a prediction (leave-one out), so it sounds like your understanding of `CCM` is right.

**Comment by nonlinearnature** [comment]
Going to weigh in on a couple of things. Starting with an "order 0" concern.

0. `tau` and effective time-series length.

Take care when experimenting with `tau` that you do not go past the limits of the data. With a time-series segment of 100 points, a `tau` of 10, and an `E` of 10 you're effectively using the entire time series to create a single state-space vector.

1. In- and out-of-sample testing.

Conventionally, I would chose all of the embedding parameters (`tau` and `E`) based on in-sample analysis with leave-one-out cross-validation (the software will do this by default). Only once you have all parameters selected would I test out-of-sample. That said, if the time series is short compared to the characteristic period of variation then it may not make sense to divide the data in half in the first place. From the sound of it you have 200 time points, but the first minimum of mutual information is at a lag of 10, suggesting that the time-series is somewhat over-sampled relative to the characteristic period of variation. The effective time-series length is probably closer 40 points like many of the fishery and oceanographic time series that EDM was developed around (e.g. Hsieh et al. 2005).

2. `tau`, `Tp`, and forecast skill

It is not surprising that forecast skill goes down when you increase `tau`, particularly if you are also changing `Tp` when you change `tau`. That is because most time series have serial autocorrelation such that very short term forecasts in an temporally over-sampled system largely reflect the inertia of the dynamics. That said, from "0." and "1." above it may also be the case that you are using embedding parameters outside of the practical limits of the time series, and therefore are really evaluating forecast skill on just a few prediction points which would make `rho` values highly prone to anomolous variation/high values.
