### ISSUE TITLE
EmbedDimension showed different results with the same amount of data input.

### ISSUE THREAD

**Issue by ecosan327** [SugiharaLab/pyEDM#40]
I have an csv file with total 1000 data points in the data_csv file, but I just want to test the embedding dimension of selected range of the data, say from data row 401 to row 560.
I tried the following two cases with the function EmbedDimension to find the optimal E.

The case 1 is to select a range of data set data_csv file from row 401~560 (from .iloc[401:561]), and choose the library and prediction length to cover the whole range of total 160 data points. 

The case 2 is to put the whole data_csv array into dataframe, but choosing library and prediction from starting row = 401 to the ending row indices = 560.

However, the E-rho result is a bit different. (See the below image)
Can anyone help me to explain why there's a difference and which method should I choose to use?

![Screenshot from 2023-05-15 10-12-03](https://github.com/SugiharaLab/pyEDM/assets/90598608/2fea16de-f1fc-450f-b394-d7a839c7ae74)

**Comment by SoftwareLiteracy** [comment]
My guess is that in case 2 a different set of embedding vectors is used than in case 1.  In case 2 the full library is available and lib and pred are selected as subsets. In case 1 the creation of the library will not be able to create the same full library from the time-delay shifting.

In the cases I tried, the code does not allow precisely what is shown. That is, an error is thrown since the prediction/library of the subset cannot create a suitable embedding. 

```python
E1 = EmbedDimension(dataFrame = sampleData['Lorenz5D'], lib = '501 550', pred = '501 550', columns = 'V1', target = 'V1', numThreads = 10)

E2 = EmbedDimension(dataFrame = sampleData['Lorenz5D'].iloc[501:550], lib = '1 50', pred = '1 50', columns = 'V1', target = 'V1', numThreads = 10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/lib/python3.10/site-packages/pyEDM/CoreEDM.py", line 488, in EmbedDimension
    D = pyBindEDM.EmbedDimension( pathIn,
RuntimeError: CheckDataRows(): PrepareEmbedding: The prediction index 50 exceeds the number of data rows 49
```
The data has to be adjusted, and the results are slightly different
```python
E2 = EmbedDimension(dataFrame = sampleData['Lorenz5D'].iloc[501:551], lib = '1 50', pred = '1 50', columns = 'V1', target = 'V1', numThreads = 10)
```
My suggestion for the best approach is to use case 2 where the full data set is available relying on lib & pred to select the desired subsets.

**Comment by ecosan327** [comment]
Thank you for the reply!

I also adjusted the data like you did in my case 1(ex: use .iloc[501:551] instead of .iloc[501:550]). I checked the dataframe when we use `sampleData['Lorenz5D'].iloc[501:551]`, only data point index from 501 to 550 are selected(data index = 551 is not selected). So I think the subset data we choose using `sampleData['Lorenz5D'].iloc[501:551]` in `E2` is the same in `E1`, right(both E1 and E2 contain totally 50 datapoints and they are data idx=1 to index=50)? Therefore the embedding vector should also be the same?

I thought with the same input data given into the function `EmbedDimension`, the result should be the same....
Or I may misunderstood something.....

**Comment by SoftwareLiteracy** [comment]
My description was not clear, and the example rather weak. Take 2:

It seems to me the time delay embedding is creating two different embeddings in the two cases. In case 2 the embedding has "lost" no vectors since the time shifting of (E-1)*tau does not "lose" data at the beginning or end of the available data rows.  

In case 1, (E-1)*tau embedding vectors are "lost" because they have vector components that were shifted from nothing and assigned nan, which are not valid vectors to be used in processing,  They are ignored. 

```python
from pyEDM import *

# 1000 row dataFrame
df = sampleData['Lorenz5D']

# 50 row subset from dataFrame
df50 = df.iloc[501:551]

# Same data in these two blocks
df.iloc[[501,550],:]
      Time      V1      V2      V3      V4      V5
501  35.05  1.0618  5.4407  9.0330  0.3704  0.0024
550  37.50 -1.6580  0.1798  0.4002  1.0539  8.4217

df50.iloc[[0,49],:]
      Time      V1      V2      V3      V4      V5
501  35.05  1.0618  5.4407  9.0330  0.3704  0.0024
550  37.50 -1.6580  0.1798  0.4002  1.0539  8.4217

# Enbed the entire df, as would be done in case 2
ebd = Embed( dataFrame = df, E = 3, columns = df.columns[1:2] )

# E - 1 "partial" vectors at the beginning from time shift
ebd.head(3)
   V1(t-0)  V1(t-1)  V1(t-2)
0   2.4873      NaN      NaN
1   3.5108   2.4873      NaN
2   4.1666   3.5108   2.4873

# Embedding vectors at rows 501, 502... are complete, not partial 
ebd.iloc[ 501:504 ]
     V1(t-0)  V1(t-1)  V1(t-2)
501   1.0618   0.7047   0.2933
502   1.4879   1.0618   0.7047
503   2.3113   1.4879   1.0618

# Embed the subset dataFrame as in case 1
ebd50 = Embed( dataFrame = df50, E = 3, columns = df.columns[1:2] )

# Embedding row corresponding to original data rows 501, 502 from
# are now a partial (unused) vector
ebd50.head(3)
   V1(t-0)  V1(t-1)  V1(t-2)
0   1.0618      NaN      NaN
1   1.4879   1.0618      NaN
2   2.3113   1.4879   1.0618
```

I think this means that case 1 does not provide the same embedding as case 2. Any partial embedding vectors are not processed.

So it seems to me that if one has data and wishes to compare subsets, case 2 is the preferred option since it will use all available data. Of course, if one compares within (E-1)*abs(tau) of the start/end of the data, some embedding vectors will be "lost" from the time delay shifting.

**Comment by ecosan327** [comment]
Oh I understand now! Thanks so much for the clarification!
