### ISSUE TITLE
Sales forecasing 

### ISSUE THREAD

**Issue by vishnu020** [SugiharaLab/pyEDM#48]
I am trying to forecast the sales for from oct 2023 to jan 2028 and i have a datset from feb 2019 to sep 2023 having total sales column and other microeconomics 

![Screenshot (52)](https://github.com/SugiharaLab/pyEDM/assets/107911588/edddc403-d4fe-4b64-9c44-d4dcaa4b3c86)
![Screenshot (53)](https://github.com/SugiharaLab/pyEDM/assets/107911588/ddb0689a-5bdc-4d11-8258-f531e4d2d4f5)
![Screenshot (54)](https://github.com/SugiharaLab/pyEDM/assets/107911588/bd2206a8-daae-413c-be8d-c524ca3d5034)
![Screenshot (55)](https://github.com/SugiharaLab/pyEDM/assets/107911588/c1f96010-ec7f-4b6f-82dd-11a213ed9ad0)
![Screenshot (56)](https://github.com/SugiharaLab/pyEDM/assets/107911588/0ed54db6-0f62-47c9-bd0a-71b56895ad2a)

 as it is predicting good on the train and test but when i am trying to forecast it is giving the null values as i don't have futures sales i have only microeconomics for that year from oct 2023 to jan 2023 .

**Comment by SoftwareLiteracy** [comment]
I'm not entirely clear on the problem. If you can provide a minimal example that can be run it would help to clarify the issue. 

Perhaps use of EDM as a predictor is not quite understood. Briefly, EDM creates (or is supplied if `embedded = True`) a state space embedding from the library of time series points (`lib`).  Predictions are made at each `pred` time series index by finding the nearest neighbors in the state space to the target at `pred`.  As mentioned in issue #47 if a target value is not known, the location in the state space from which a prediction is made is not known, a prediction can not be made. 

You may note that `Tp` is the prediction interval.  If `Tp > 0` then a forecast is made at `Tp` points ahead in time.  This is how one can forecast beyond the data.  Of course, in a nonlinear system one does not expect good forecast fidelity at large `Tp`.  The `PredictInterval` function can illustrate this. 

Another nuance reflective of the degradation in prediction skill of a nonlinear system as `Tp` increases is that while forecasting with say `Tp = 7` does give forecast values at 7 time steps ahead, the values at `Tp = 1,2..` will not be as accurate as those made with `Tp = 1`, `Tp = 2`... since nearest neighbors are being selected farther away than would be done with `Tp = 1`, `Tp = 2`...  In this case one might compute a separate forecast for each `Tp` of interest taking the final value at `Tp` from each forecast. 

Also, `Multiview` is not normally used directly for prediction/forecasting. It is typically used to select the most informative variables, then `Simplex` or `SMap` are used for specific prediction/forecasting.  Since `Multiview` is computationally intensive, use of the `numThreads` parameter can help.
