### ISSUE TITLE
SMap producing different results in different environments

### ISSUE THREAD

**Issue by asb24repo** [SugiharaLab/pyEDM#49]
I am running the exact same code and data on Google Colab and Jupyter notebook.
The plots for the SMap are different in both.
Results in Colab:
![image](https://github.com/SugiharaLab/pyEDM/assets/98976032/96949d39-fdd6-4489-a7c9-6a4af73780cd)
Results in Jupyter:
![image](https://github.com/SugiharaLab/pyEDM/assets/98976032/39f7bc55-faac-4fca-be4e-eb96a9741c28)

They have the same version on both.
Help is appreciated.

**Comment by asb24repo** [comment]
Downgrading to version 1.14.3 solved the issue. Would this mean that sklearn is not stable? Does it have any random seeds?

**Comment by SoftwareLiteracy** [comment]
It's just that the Windog build was forced to switch from direct BLAS/LAPACK to sklearn for the SMap solver since Windog does not natively support BLAS/LAPACK, so the matrix inversion routine is not the same. There are no random seeds. 

You can try another sklearn solver as documented in the [SMap docs](https://sugiharalab.github.io/EDM_Documentation/smap_/) Linear System Solver section, and [examples](https://sugiharalab.github.io/EDM_Documentation/solvers_demo/).  For ill-conditioned systems these may work better.  For well-conditioned systems the results should be the same.
